version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: main
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Bratislava
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: daily
      time: '07:00'
      timezone: Europe/Bratislava
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
